/* Generated by tools/generate-hsa-stubs.pl — do not edit by hand.
 * Source header: third_party/rocr-headers/hsa/hsa.h
 */
#define HSA_EXPORT
#include "hsa.h"

/* auto-stub */
hsa_status_t HSA_API hsa_extension_get_name(
    uint16_t extension,
    const char **name)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_system_major_extension_supported(
    uint16_t extension,
    uint16_t version_major,
    uint16_t *version_minor,
    bool* result)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_system_get_major_extension_table(
    uint16_t extension,
    uint16_t version_major,
    size_t table_length,
    void *table)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_cache_get_info(
    hsa_cache_t cache,
    hsa_cache_info_t attribute,
    void* value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_agent_iterate_caches(
    hsa_agent_t agent,
    hsa_status_t (*callback)(hsa_cache_t cache, void* data),
    void* data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_agent_major_extension_supported(
    uint16_t extension,
    hsa_agent_t agent,
    uint16_t version_major,
    uint16_t *version_minor,
    bool* result)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
void HSA_API hsa_signal_silent_store_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_silent_store_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_exchange_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_exchange_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_exchange_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_exchange_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_cas_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t expected,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_cas_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t expected,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_cas_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t expected,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
hsa_signal_value_t HSA_API hsa_signal_cas_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t expected,
    hsa_signal_value_t value)
{
  return (hsa_signal_value_t)0;
}

/* auto-stub */
void HSA_API hsa_signal_add_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_add_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_add_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_add_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_subtract_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_subtract_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_subtract_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_subtract_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_and_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_and_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_and_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_and_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_or_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_or_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_or_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_or_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_xor_scacq_screl(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_xor_scacquire(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_xor_relaxed(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
void HSA_API hsa_signal_xor_screlease(
    hsa_signal_t signal,
    hsa_signal_value_t value)
{
  /* SoftGPU: unsupported void API */
}

/* auto-stub */
hsa_status_t HSA_API hsa_signal_group_create(
    uint32_t num_signals,
    const hsa_signal_t *signals,
    uint32_t num_consumers,
    const hsa_agent_t *consumers,
    hsa_signal_group_t *signal_group)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_signal_group_destroy(
    hsa_signal_group_t signal_group)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_signal_group_wait_any_scacquire(
    hsa_signal_group_t signal_group,
    const hsa_signal_condition_t *conditions,
    const hsa_signal_value_t *compare_values,
    hsa_wait_state_t wait_state_hint,
    hsa_signal_t *signal,
    hsa_signal_value_t *value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_signal_group_wait_any_relaxed(
    hsa_signal_group_t signal_group,
    const hsa_signal_condition_t *conditions,
    const hsa_signal_value_t *compare_values,
    hsa_wait_state_t wait_state_hint,
    hsa_signal_t *signal,
    hsa_signal_value_t *value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_soft_queue_create(
    hsa_region_t region,
    uint32_t size,
    hsa_queue_type32_t type,
    uint32_t features,
    hsa_signal_t doorbell_signal,
    hsa_queue_t **queue)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_queue_inactivate(
    hsa_queue_t *queue)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_cas_write_index_scacq_screl(
    const hsa_queue_t *queue,
    uint64_t expected,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_cas_write_index_scacquire(
    const hsa_queue_t *queue,
    uint64_t expected,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_cas_write_index_relaxed(
    const hsa_queue_t *queue,
    uint64_t expected,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_cas_write_index_screlease(
    const hsa_queue_t *queue,
    uint64_t expected,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_add_write_index_scacq_screl(
    const hsa_queue_t *queue,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_add_write_index_scacquire(
    const hsa_queue_t *queue,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_add_write_index_relaxed(
    const hsa_queue_t *queue,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
uint64_t HSA_API hsa_queue_add_write_index_screlease(
    const hsa_queue_t *queue,
    uint64_t value)
{
  return (uint64_t)0;
}

/* auto-stub */
hsa_status_t HSA_API hsa_memory_assign_agent(
    void *ptr,
    hsa_agent_t agent,
    hsa_access_permission_t access)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_memory_register(
    void *ptr,
    size_t size)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_memory_deregister(
    void *ptr,
    size_t size)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_isa_from_name(
    const char *name,
    hsa_isa_t *isa)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_agent_iterate_isas(
    hsa_agent_t agent,
    hsa_status_t (*callback)(hsa_isa_t isa, void *data),
    void *data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_isa_get_info_alt(
    hsa_isa_t isa,
    hsa_isa_info_t attribute,
    void *value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_isa_get_exception_policies(
    hsa_isa_t isa,
    hsa_profile_t profile,
    uint16_t *mask)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_isa_get_round_method(
    hsa_isa_t isa,
    hsa_fp_type_t fp_type,
    hsa_flush_mode_t flush_mode,
    hsa_round_method_t *round_method)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_wavefront_get_info(
    hsa_wavefront_t wavefront,
    hsa_wavefront_info_t attribute,
    void *value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_isa_iterate_wavefronts(
    hsa_isa_t isa,
    hsa_status_t (*callback)(hsa_wavefront_t wavefront, void *data),
    void *data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_code_object_reader_create_from_file(
    hsa_file_t file,
    hsa_code_object_reader_t *code_object_reader)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_code_object_reader_create_from_memory(
    const void *code_object,
    size_t size,
    hsa_code_object_reader_t *code_object_reader)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_code_object_reader_destroy(
    hsa_code_object_reader_t code_object_reader)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_create_alt(
    hsa_profile_t profile,
    hsa_default_float_rounding_mode_t default_float_rounding_mode,
    const char *options,
    hsa_executable_t *executable)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_destroy(
    hsa_executable_t executable)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_load_program_code_object(
    hsa_executable_t executable,
    hsa_code_object_reader_t code_object_reader,
    const char *options,
    hsa_loaded_code_object_t *loaded_code_object)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_load_agent_code_object(
    hsa_executable_t executable,
    hsa_agent_t agent,
    hsa_code_object_reader_t code_object_reader,
    const char *options,
    hsa_loaded_code_object_t *loaded_code_object)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_freeze(
    hsa_executable_t executable,
    const char *options)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_get_info(
    hsa_executable_t executable,
    hsa_executable_info_t attribute,
    void *value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_global_variable_define(
    hsa_executable_t executable,
    const char *variable_name,
    void *address)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_agent_global_variable_define(
    hsa_executable_t executable,
    hsa_agent_t agent,
    const char *variable_name,
    void *address)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_readonly_variable_define(
    hsa_executable_t executable,
    hsa_agent_t agent,
    const char *variable_name,
    void *address)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_validate(
    hsa_executable_t executable,
    uint32_t *result)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_validate_alt(
    hsa_executable_t executable,
    const char *options,
    uint32_t *result)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_get_symbol_by_name(
    hsa_executable_t executable,
    const char *symbol_name,
    const hsa_agent_t *agent,
    hsa_executable_symbol_t *symbol)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_symbol_get_info(
    hsa_executable_symbol_t executable_symbol,
    hsa_executable_symbol_info_t attribute,
    void *value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_iterate_agent_symbols(
    hsa_executable_t executable,
    hsa_agent_t agent,
    hsa_status_t (*callback)(hsa_executable_t exec,
                             hsa_agent_t agent,
                             hsa_executable_symbol_t symbol,
                             void *data),
    void *data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_executable_iterate_program_symbols(
    hsa_executable_t executable,
    hsa_status_t (*callback)(hsa_executable_t exec,
                             hsa_executable_symbol_t symbol,
                             void *data),
    void *data)
{
  return HSA_STATUS_ERROR;
}

/* generated stub count: 78 */
