/* Generated by tools/generate-hsa-stubs.pl — do not edit by hand.
 * Source header: third_party/rocr-headers/hsa/hsa_ext_amd.h
 */
#define HSA_EXPORT
#include "hsa_ext_amd.h"

/* auto-stub */
hsa_status_t HSA_API hsa_amd_coherency_get_type(hsa_agent_t agent,
                                                hsa_amd_coherency_type_t* type)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_coherency_set_type(hsa_agent_t agent,
                                                hsa_amd_coherency_type_t type)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_profiling_set_profiler_enabled(hsa_queue_t* queue, int enable)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_profiling_async_copy_enable(bool enable)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_agent_preload(hsa_agent_t agent, uint64_t flags)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_profiling_get_dispatch_time(
    hsa_agent_t agent, hsa_signal_t signal,
    hsa_amd_profiling_dispatch_time_t* time)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_profiling_get_async_copy_time(
    hsa_signal_t signal, hsa_amd_profiling_async_copy_time_t* time)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_profiling_convert_tick_to_system_domain(hsa_agent_t agent,
                                                    uint64_t agent_tick,
                                                    uint64_t* system_tick)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_signal_create(hsa_signal_value_t initial_value, uint32_t num_consumers,
                                           const hsa_agent_t* consumers, uint64_t attributes,
                                           hsa_signal_t* signal)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_signal_async_handler(hsa_signal_t signal,
                                 hsa_signal_condition_t cond,
                                 hsa_signal_value_t value,
                                 hsa_amd_signal_handler handler, void* arg)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
uint32_t HSA_API hsa_amd_signal_wait_all(uint32_t signal_count, hsa_signal_t* signals,
                                         hsa_signal_condition_t* conds, hsa_signal_value_t* values,
                                         uint64_t timeout_hint, hsa_wait_state_t wait_hint,
                                         hsa_signal_value_t* satisfying_values)
{
  return (uint32_t)0;
}

/* auto-stub */
uint32_t HSA_API hsa_amd_signal_wait_any(uint32_t signal_count, hsa_signal_t* signals,
                            hsa_signal_condition_t* conds,
                            hsa_signal_value_t* values, uint64_t timeout_hint,
                            hsa_wait_state_t wait_hint,
                            hsa_signal_value_t* satisfying_value)
{
  return (uint32_t)0;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_signal_get_event_id(hsa_signal_t signal, uint32_t *event_id)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_async_function(void (*callback)(void* arg), void* arg)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_image_create(
    hsa_agent_t agent,
    const hsa_ext_image_descriptor_t *image_descriptor,
    const hsa_amd_image_descriptor_t *image_layout,
    const void *image_data,
    hsa_access_permission_t access_permission,
    hsa_ext_image_t *image
)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_image_create_v2(
    hsa_agent_t agent,
    const hsa_ext_image_descriptor_v2_t* image_descriptor,
    const hsa_amd_image_descriptor_t* image_layout,
    const void* image_data,
    hsa_access_permission_t access_permission,
    hsa_ext_image_t* image)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_image_get_info_max_dim(hsa_agent_t agent,
                                                    hsa_agent_info_t attribute,
                                                    void* value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_queue_cu_set_mask(const hsa_queue_t* queue,
                                               uint32_t num_cu_mask_count,
                                               const uint32_t* cu_mask)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_queue_cu_get_mask(const hsa_queue_t* queue, uint32_t num_cu_mask_count,
                                               uint32_t* cu_mask)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_pool_get_info(hsa_amd_memory_pool_t memory_pool,
                                 hsa_amd_memory_pool_info_t attribute,
                                 void* value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_agent_iterate_memory_pools(
    hsa_agent_t agent,
    hsa_status_t (*callback)(hsa_amd_memory_pool_t memory_pool, void* data),
    void* data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_pool_allocate(hsa_amd_memory_pool_t memory_pool, size_t size,
                                 uint32_t flags, void** ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_pool_free(void* ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_async_copy(void* dst, hsa_agent_t dst_agent, const void* src,
                              hsa_agent_t src_agent, size_t size,
                              uint32_t num_dep_signals,
                              const hsa_signal_t* dep_signals,
                              hsa_signal_t completion_signal)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_async_copy_on_engine(void* dst, hsa_agent_t dst_agent, const void* src,
                              hsa_agent_t src_agent, size_t size,
                              uint32_t num_dep_signals,
                              const hsa_signal_t* dep_signals,
                              hsa_signal_t completion_signal,
                              hsa_amd_sdma_engine_id_t engine_id,
                              bool force_copy_on_sdma)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_async_batch_copy(const hsa_amd_memory_copy_op_t* copy_ops,
                              uint32_t num_copy_ops,
                              uint32_t num_dep_signals,
                              const hsa_signal_t* dep_signals)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_copy_engine_status(hsa_agent_t dst_agent, hsa_agent_t src_agent,
                                      uint32_t *engine_ids_mask)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_get_preferred_copy_engine(hsa_agent_t dst_agent, hsa_agent_t src_agent,
                                         uint32_t* recommended_ids_mask)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_async_copy_rect(
    const hsa_pitched_ptr_t* dst, const hsa_dim3_t* dst_offset, const hsa_pitched_ptr_t* src,
    const hsa_dim3_t* src_offset, const hsa_dim3_t* range, hsa_agent_t copy_agent,
    hsa_amd_copy_direction_t dir, uint32_t num_dep_signals, const hsa_signal_t* dep_signals,
    hsa_signal_t completion_signal)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_agent_memory_pool_get_info(
    hsa_agent_t agent, hsa_amd_memory_pool_t memory_pool,
    hsa_amd_agent_memory_pool_info_t attribute, void* value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_agents_allow_access(uint32_t num_agents, const hsa_agent_t* agents,
                                const uint32_t* flags, const void* ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_pool_can_migrate(hsa_amd_memory_pool_t src_memory_pool,
                                    hsa_amd_memory_pool_t dst_memory_pool,
                                    bool* result)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_migrate(const void* ptr,
                                            hsa_amd_memory_pool_t memory_pool,
                                            uint32_t flags)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_lock(void* host_ptr, size_t size,
                                         hsa_agent_t* agents, int num_agent,
                                         void** agent_ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_lock_to_pool(void* host_ptr, size_t size, hsa_agent_t* agents,
                                                 int num_agent, hsa_amd_memory_pool_t pool,
                                                 uint32_t flags, void** agent_ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_unlock(void* host_ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_memory_fill(void* ptr, uint32_t value, size_t count)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_interop_map_buffer(uint32_t num_agents, hsa_agent_t* agents,
                                                hsa_handle_t interop_handle, uint32_t flags,
                                                size_t* size, void** ptr, size_t* metadata_size,
                                                const void** metadata)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_interop_map_buffer_with_size(
    uint32_t num_agents, hsa_agent_t* agents, hsa_handle_t interop_handle, uint32_t flags,
    size_t size_hint, size_t* size, void** ptr, size_t* metadata_size, const void** metadata)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_interop_unmap_buffer(void* ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_pointer_info(const void* ptr,
                                          hsa_amd_pointer_info_t* info,
                                          void* (*alloc)(size_t),
                                          uint32_t* num_agents_accessible,
                                          hsa_agent_t** accessible)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_pointer_info_set_userdata(const void* ptr,
                                                       void* userdata)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ipc_memory_create(void* ptr, size_t len,
                                               hsa_amd_ipc_memory_t* handle)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ipc_memory_attach(
    const hsa_amd_ipc_memory_t* handle, size_t len,
    uint32_t num_agents,
    const hsa_agent_t* mapping_agents,
    void** mapped_ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ipc_memory_detach(void* mapped_ptr)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_external_semaphore_handle_open(
    hsa_agent_t agent,
    const hsa_amd_external_semaphore_handle_descriptor_t *desc,
    hsa_amd_external_semaphore_t *out_sem)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_external_semaphore_handle_close(
    hsa_amd_external_semaphore_t sem)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_queue_signal_external_semaphore(
    hsa_queue_t                  *queue,
    hsa_amd_external_semaphore_t  sem,
    uint64_t                      value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_queue_wait_external_semaphore(
    hsa_queue_t                  *queue,
    hsa_amd_external_semaphore_t  sem,
    uint64_t                      value)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ipc_signal_create(hsa_signal_t signal, hsa_amd_ipc_signal_t* handle)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ipc_signal_attach(const hsa_amd_ipc_signal_t* handle,
                                               hsa_signal_t* signal)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_register_system_event_handler(hsa_amd_system_event_callback_t callback,
                                                   void* data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_queue_set_priority(hsa_queue_t* queue,
                                                hsa_amd_queue_priority_t priority)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_queue_create(
    hsa_agent_t agent,
    hsa_amd_queue_create_desc_t *descs,
    uint32_t num_descs)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_register_deallocation_callback(void* ptr,
                                                    hsa_amd_deallocation_callback_t callback,
                                                    void* user_data)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_deregister_deallocation_callback(void* ptr,
                                                      hsa_amd_deallocation_callback_t callback)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_svm_discard_batch_async(void** ptrs, size_t* sizes, uint32_t count,
                                                     uint32_t num_dep_signals,
                                                     const hsa_signal_t* dep_signals,
                                                     hsa_signal_t completion_signal)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_svm_discard_and_prefetch_batch_async(
    void** ptrs, size_t* sizes, uint32_t count,
    const hsa_agent_t* dst_agents, uint32_t num_dst_agents,
    uint32_t num_dep_signals, const hsa_signal_t* dep_signals,
    hsa_signal_t completion_signal)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_agent_set_async_scratch_limit(hsa_agent_t agent, size_t threshold)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ais_file_write(hsa_amd_ais_file_handle_t handle, void *devicePtr,
                                            uint64_t size, int64_t file_offset,
                                            uint64_t *size_copied, int32_t *status)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_ais_file_read(hsa_amd_ais_file_handle_t handle, void *devicePtr,
                                           uint64_t size, int64_t file_offset,
                                           uint64_t *size_copied, int32_t *status)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_counted_queue_acquire(hsa_agent_t agent, hsa_queue_type_t type,
                                           hsa_amd_queue_priority_t priority,
                                           void (*callback)(hsa_status_t status,
                                                            hsa_queue_t* source, void* data),
                                           void* data, uint64_t flags, hsa_queue_t** queue)
{
  return HSA_STATUS_ERROR;
}

/* auto-stub */
hsa_status_t HSA_API hsa_amd_counted_queue_release(hsa_queue_t* queue)
{
  return HSA_STATUS_ERROR;
}

/* generated stub count: 63 */
