//! Static status strings for `hsa_status_string`.

use crate::ffi::{
    hsa_status_t, HSA_STATUS_ERROR, HSA_STATUS_ERROR_INVALID_AGENT,
    HSA_STATUS_ERROR_INVALID_ARGUMENT, HSA_STATUS_ERROR_NOT_INITIALIZED,
    HSA_STATUS_ERROR_REFCOUNT_OVERFLOW, HSA_STATUS_INFO_BREAK, HSA_STATUS_SUCCESS,
};
use std::ffi::CStr;

pub fn status_string(status: hsa_status_t) -> &'static CStr {
    match status {
        HSA_STATUS_SUCCESS => c"HSA_STATUS_SUCCESS",
        HSA_STATUS_INFO_BREAK => c"HSA_STATUS_INFO_BREAK",
        HSA_STATUS_ERROR => c"HSA_STATUS_ERROR",
        HSA_STATUS_ERROR_INVALID_ARGUMENT => c"HSA_STATUS_ERROR_INVALID_ARGUMENT",
        HSA_STATUS_ERROR_INVALID_AGENT => c"HSA_STATUS_ERROR_INVALID_AGENT",
        HSA_STATUS_ERROR_NOT_INITIALIZED => c"HSA_STATUS_ERROR_NOT_INITIALIZED",
        HSA_STATUS_ERROR_REFCOUNT_OVERFLOW => c"HSA_STATUS_ERROR_REFCOUNT_OVERFLOW",
        _ => c"HSA_STATUS_ERROR (SoftGPU unrecognized status)",
    }
}
