//! Static status strings for `hsa_status_string`.

use crate::ffi::{
    hsa_status_t, HSA_STATUS_ERROR, HSA_STATUS_ERROR_INVALID_AGENT,
    HSA_STATUS_ERROR_INVALID_ALLOCATION, HSA_STATUS_ERROR_INVALID_ARGUMENT,
    HSA_STATUS_ERROR_INVALID_MEMORY_POOL, HSA_STATUS_ERROR_INVALID_QUEUE,
    HSA_STATUS_ERROR_INVALID_QUEUE_CREATION, HSA_STATUS_ERROR_INVALID_REGION,
    HSA_STATUS_ERROR_INVALID_SIGNAL, HSA_STATUS_ERROR_NOT_INITIALIZED,
    HSA_STATUS_ERROR_OUT_OF_RESOURCES, HSA_STATUS_ERROR_REFCOUNT_OVERFLOW, HSA_STATUS_INFO_BREAK,
    HSA_STATUS_SUCCESS,
};
use std::ffi::CStr;

pub fn status_string(status: hsa_status_t) -> &'static CStr {
    match status {
        HSA_STATUS_SUCCESS => c"HSA_STATUS_SUCCESS",
        HSA_STATUS_INFO_BREAK => c"HSA_STATUS_INFO_BREAK",
        HSA_STATUS_ERROR => c"HSA_STATUS_ERROR",
        HSA_STATUS_ERROR_INVALID_ARGUMENT => c"HSA_STATUS_ERROR_INVALID_ARGUMENT",
        HSA_STATUS_ERROR_INVALID_QUEUE_CREATION => c"HSA_STATUS_ERROR_INVALID_QUEUE_CREATION",
        HSA_STATUS_ERROR_INVALID_ALLOCATION => c"HSA_STATUS_ERROR_INVALID_ALLOCATION",
        HSA_STATUS_ERROR_INVALID_AGENT => c"HSA_STATUS_ERROR_INVALID_AGENT",
        HSA_STATUS_ERROR_INVALID_REGION => c"HSA_STATUS_ERROR_INVALID_REGION",
        HSA_STATUS_ERROR_INVALID_SIGNAL => c"HSA_STATUS_ERROR_INVALID_SIGNAL",
        HSA_STATUS_ERROR_INVALID_QUEUE => c"HSA_STATUS_ERROR_INVALID_QUEUE",
        HSA_STATUS_ERROR_OUT_OF_RESOURCES => c"HSA_STATUS_ERROR_OUT_OF_RESOURCES",
        HSA_STATUS_ERROR_NOT_INITIALIZED => c"HSA_STATUS_ERROR_NOT_INITIALIZED",
        HSA_STATUS_ERROR_REFCOUNT_OVERFLOW => c"HSA_STATUS_ERROR_REFCOUNT_OVERFLOW",
        HSA_STATUS_ERROR_INVALID_MEMORY_POOL => c"HSA_STATUS_ERROR_INVALID_MEMORY_POOL",
        _ => c"HSA_STATUS_ERROR (SoftGPU unrecognized status)",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_and_unknown_status_strings() {
        assert_eq!(
            status_string(HSA_STATUS_SUCCESS).to_bytes(),
            b"HSA_STATUS_SUCCESS"
        );
        assert_eq!(
            status_string(HSA_STATUS_ERROR_NOT_INITIALIZED).to_bytes(),
            b"HSA_STATUS_ERROR_NOT_INITIALIZED"
        );
        assert_eq!(
            status_string(HSA_STATUS_ERROR_INVALID_MEMORY_POOL).to_bytes(),
            b"HSA_STATUS_ERROR_INVALID_MEMORY_POOL"
        );
        assert!(status_string(0xDEAD_u32)
            .to_str()
            .unwrap()
            .contains("unrecognized"));
    }
}
