#!/usr/bin/env perl
# Generate honest fail-closed C stubs for HSA APIs SoftGPU does not implement.
use strict;
use warnings;

my $header = $ARGV[0] // die "usage: $0 <header.h> <out.c> <include-line>\n";
my $out    = $ARGV[1] // die "usage: $0 <header.h> <out.c> <include-line>\n";
my $inc    = $ARGV[2] // '#include "hsa/hsa.h"';

my %implemented = map { $_ => 1 } qw(
  hsa_init
  hsa_shut_down
  hsa_iterate_agents
  hsa_agent_get_info
  hsa_status_string
  hsa_system_get_info
);

open my $fh, '<', $header or die "read $header: $!";
local $/;
my $text = <$fh>;
close $fh;

$text =~ s{/\*.*?\*/}{}gs;
$text =~ s{//.*?$}{}gm;

my @stubs;
while ($text =~ /
  ((?:hsa_status_t|void|hsa_signal_value_t|uint64_t|uint32_t|int|bool|hsa_amd_pointer_status_t)\s+)
  HSA_API\s+
  (hsa_[A-Za-z0-9_]+)\s*
  (\([^;]*\))\s*;
/gx) {
  my ($ret, $name, $args) = ($1, $2, $3);
  $ret =~ s/\s+$//;
  next if $implemented{$name};
  my $body;
  if ($ret eq 'void') {
    $body = "{\n  /* SoftGPU: unsupported void API */\n}\n";
  } elsif ($ret eq 'hsa_status_t' || $ret eq 'hsa_amd_pointer_status_t') {
    $body = "{\n  return HSA_STATUS_ERROR;\n}\n";
  } elsif ($ret eq 'bool') {
    $body = "{\n  return false;\n}\n";
  } else {
    $body = "{\n  return ($ret)0;\n}\n";
  }
  push @stubs, "/* auto-stub */\n$ret HSA_API $name$args\n$body";
}

open my $outfh, '>', $out or die "write $out: $!";
print $outfh <<"HDR";
/* Generated by tools/generate-hsa-stubs.pl — do not edit by hand.
 * Source header: $header
 */
#define HSA_EXPORT
$inc

HDR
print $outfh join("\n", @stubs);
print $outfh "\n/* generated stub count: ", scalar(@stubs), " */\n";
close $outfh;
print "wrote $out (", scalar(@stubs), " stubs)\n";
